---
- name: Clear redfish job queues
  become: yes
  shell: podman run -it --rm quay.io/quads/badfish --host-list /bad-hosts -u quads -p {{ chassis_password }} --clear-jobs --force
  register: clear_jobs
  until: clear_jobs is succeeded
  retries: 3
  delay: 30

- name: Wait for iDrac to be responsive
  become: yes
  shell: podman run -it --rm quay.io/quads/badfish --host-list /bad-hosts -u quads -p {{ chassis_password }} -i config/idrac_interfaces.yml --check-boot
  register: wait_for_idrac
  until: wait_for_idrac is succeeded
  retries: 20
  delay: 30

- name: set boot order director (badfish)
  become: yes
  shell: podman run -it --rm quay.io/quads/badfish --host-list /bad-hosts -u quads -p {{ chassis_password }} -i config/idrac_interfaces.yml -t director
  retries: 5
  delay: 3
  register: result
  until: result.rc == 0

- name: power cycle overcloud nodes
  become: yes
  shell: podman run -it --rm quay.io/quads/badfish --host-list /bad-hosts -u quads -p {{ chassis_password }} --power-cycle

- name: Wait for iDrac to be responsive
  become: yes
  shell: podman run -it --rm quay.io/quads/badfish --host-list /bad-hosts -u quads -p {{ chassis_password }} -i config/idrac_interfaces.yml --check-boot
  register: wait_for_idrac
  until: wait_for_idrac is succeeded
  retries: 20
  delay: 30
